### ISSUE TITLE
Export to PNG scrambles text

### ISSUE THREAD

**Issue by GoogleCodeExporter** [bancika/diy-layout-creator#130] opened 2015-03-27 15:10 UTC
```
What steps will reproduce the problem?
1. Unknown, as it seems to be intermittent. 

What is the expected output? I exported a .png, expecting to be able to view 
the appropriate image.

What do you see instead? The board and components were as placed in the .diy 
file, but the text was all over the place. None of the letters were scrambled, 
but their locations were very inaccurate. However, it has been intermittent and 
I have been able to repeat the "export .png" function until it exports properly.

I have attached the log file from 3/7, which was the date I was having the 
issue.

What version of the product are you using? The new beta. On what operating 
system? Windows 7.


Please provide any additional information below.


```

Original issue reported on code.google.com by `mrs...@case.edu` on 9 Mar 2012 at 2:57

Attachments:
- [log-Wed Mar 07 11.11.27 EST 2012.log](https://storage.googleapis.com/google-code-attachments/diy-layout-creator/issue-130/comment-0/log-Wed Mar 07 11.11.27 EST 2012.log)

**Comment by bancika** [comment] 2017-04-22 18:58
not able to reproduce, closing for now

**Closed by bancika** 2017-04-22 18:58 UTC
Labels: auto-migrated, Priority-Medium, Type-Defect
