### ISSUE TITLE
(MacOS) .app won't open

### ISSUE THREAD

**Issue by martinloren** [bancika/diy-layout-creator#357] opened 2018-06-27 02:21 UTC
The JavaApplicationStub file seems corrupted. System message on opening:

“JavaApplicationStub” is damaged and can’t be opened. You should move it to the Trash.

File diylc.jar can open and the App works correctly. Please fix the Stub file, thanks!

**Comment by jonathanfann** [comment] 2018-10-06 17:05
https://github.com/bancika/diy-layout-creator/issues/364#issuecomment-427589732 i made this automator workflow if you're interested in how

**Comment by bancika** [comment] 2018-12-16 17:08
dupe of #364

**Closed by bancika** 2018-12-16 17:08 UTC
