### ISSUE TITLE
OSX sidebar/tree bug

### ISSUE THREAD

**Issue by MacFly77** [bancika/diy-layout-creator#416] opened 2019-01-25 17:25 UTC
Great to have V3.50 here!

There is a thing that still bugs me. 
On OSX 10.11.6, Java 8 201 the sidebar/searchable tree graphics are incorrect when scrolling.
See the attached image. Scrolling slowly helps to refresh....but still.

<img width="1050" alt="schermafbeelding 2019-01-25 om 18 21 11" src="https://user-images.githubusercontent.com/34584975/51761756-3a00e600-20ce-11e9-8ddf-b7f3767d744c.png">

**Comment by FentonBresler** [comment] 2019-03-13 02:18
Still an issue here in 3.56.0

**Comment by bancika** [comment] 2020-03-27 22:41
Does it still happen with version 4 and upgraded Java? I can't reproduce it on Catalina.

**Comment by bancika** [comment] 2020-11-19 17:38
the tree was recently rewritten from scratch. Closing for now, please reopen if still an issue.

**Closed by bancika** 2020-11-19 17:38 UTC
