### ISSUE TITLE
Show connectivity between nodes

### ISSUE THREAD

**Issue by GoogleCodeExporter** [bancika/diy-layout-creator#232] opened 2015-03-27 15:12 UTC
```
As an enhancement it would be of great help if one could highlight all 
connected nodes if one hovers over one. The algorithm should follow jumpers, 
vero tracks, wire and traces.
```

Original issue reported on code.google.com by `arnoud.p...@gmail.com` on 17 Jul 2013 at 2:18

**Comment by bancika** [comment] 2018-12-16 00:14
dupe of #344

**Closed by bancika** 2018-12-16 00:14 UTC
Labels: Priority-Medium, Type-Defect, auto-migrated
